apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-api
  template:
    metadata:
      labels:
        app: genai-api
    spec:
      containers:
        - name: genai-api
          image: genai-api:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: main-config
